### ISSUE TITLE
Zabbix 5.2.4 & 5.2.5

### ISSUE THREAD

**Issue by rudolfkastl** [haught/zbx_gchat#1]
When clicking test to test the media:

Media type test failed.
Sending failed: Incorrect "event_source" parameter given: "{EVENT.SOURCE}".
Must be 0-3.

**Comment by haught** [comment]
When you go to test a media type you are presented with a bunch of variables that you can fill out. By default they look something {EVENT.SOURCE}. When an actual real alert is produced those variables are filled out by zabbix. The media type expects some of these to be filled out so it can choose how to display an alert.

Here is an example of the message variables you can set to test:

event_source  =  1
alert_subject = Test alert
alert_message = This is an alert message
host_name = myhost.example.com
host_ip = 10.10.10.10

The required variables change depending on the event_source or other variables but this example will allow you to test things at least from a connection standpoint.

**Comment by rudolfkastl** [comment]
Thank you! That worked like a charm. May i recommend to add this to the README document as a connection test info? I am sure it is helpful for others too. One additional question, when i add a user for the alerts, what is the "send to" mandatory field supposed to be like? Should it add the webhook url again?

**Comment by rudolfkastl** [comment]
The entry "send to" does not seem to add anything important. The problem can be closed! Thank you! Everything works like a charm.
